version: '3.9'

services:
  mongo:
    image: mongo:bionic
    command: --replSet rs0
    ports:
      - "27017:27017"
    container_name: mongo

  redis:
    restart: always
    image: 'redis:latest'
    ports:
      - '6379:6379'
    container_name: redis
