services:
  mongodb:
    restart: always
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=spots'
    ports:
      - '27017:27017'
  redis:
    restart: always
    image: 'redis:latest'
    ports:
      - '6379:6379'
