logging:
  level:
    org:
      springframework:
        security: DEBUG
server:
  port: 8080
  servlet:
    context-path: /api
spring:
  mail:
    host:
      smtp.gmail.com
    port: 587
    username: ivanivanov.ii726@gmail.com
    password: uqrn mrsw erke wbhn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    mongodb:
      uri: mongodb://localhost:27017/spots
    redis:
      host: localhost
      port: 6379

application:
  security:
    jwt:
      secret-key: ${SPOTS_SECRET}
      expiration: 86400000 # a day