logging:
  level:
    org:
      springframework:
        security: DEBUG
server:
  port: 8080
  servlet:
    context-path: /api
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 797689781814-s00krb448l8t1vpev47i5k8br6mcp7f9.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "http://localhost:8080/api/test"
#          facebook:
#            client-id: 1320177058609022
#            client-secret: 2e19874fb67a7c7d99edaeeaf801677e
#            scope:
#              - user_profile
#              - user_media
#            redirectUri: "https://localhost:8080/api/test"
#        provider:
#          facebook:
#            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
#            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
  data:
    mongodb:
      uri: mongodb://localhost:27017/spots
    redis:
      host: localhost
      port: 6379
application:
  security:
    jwt:
      secret-key: ${SPOTS_SECRET}
      expiration: 86400000 # a day
