#!/bin/sh

echo "*****Running unit tests******"

./gradlew spotlessApply --daemon

git add .
git stash -q --keep-index

./gradlew test

status=$?

git stash pop -q

echo "*****Done with unit tests******"

exit $status